### ISSUE TITLE
Easy compilation

### ISSUE THREAD

**Issue by IamMuuo** [musaubrian/maze_runner#1]
# Easy Compilation
Hey im interested in contributing this project although its not setup well for compilation could you use a proper build system such as cmake, ninja or whatever

**Comment by musaubrian** [comment]
Not sure how to do that, just used a MakeFile, to get it to work.
Could you help set it up?

**Comment by IamMuuo** [comment]
There's no makefile
And if youre calling the setup.sh script a makefile please don't

**Comment by musaubrian** [comment]
No I'm not, the setupSDL.sh was for installing the SDL library.

[makefile](https://github.com/musaubrian/maze_runner/blob/main/Makefile)

And again I did say you could help set it up, not well versed in the game universe

**Comment by IamMuuo** [comment]
OK ill try set it up  and make a PR

**Comment by IamMuuo** [comment]
Just made a PR that adds cmake

**Comment by musaubrian** [comment]
Thanks, just merged it
